import listing1 from "@/assets/listing-1.jpg";
import listing2 from "@/assets/listing-2.jpg";
import listing3 from "@/assets/listing-3.jpg";

export interface PropertyListing {
  id: string;
  title: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  price: number;
  priceType: "sale" | "lease";
  beds: number;
  baths: number;
  sqft: number;
  lotSize?: string;
  yearBuilt?: number;
  propertyType: "Single Family Home" | "Townhouse" | "Condo" | "Land" | "Multi-Family";
  status: "For Sale" | "For Lease" | "Pending" | "Sold" | "Inactive";
  featured: boolean;
  description: string;
  features: string[];
  images: string[];
  virtualTourUrl?: string;
  matterportUrl?: string;
  hoaFee?: number;
  garage?: number;
  stories?: number;
  heating?: string;
  cooling?: string;
  flooring?: string[];
  appliances?: string[];
  neighborhood?: string;
  school_district?: string;
  latitude?: number;
  longitude?: number;
  mlsNumber?: string;
  daysOnMarket?: number;
}

export const allListings: PropertyListing[] = [
  // ACTIVE LISTINGS
  {
    id: "10507-halley-lane",
    title: "Stunning 5-Bedroom Estate in Richmond",
    address: "10507 Halley Lane",
    city: "Richmond",
    state: "TX",
    zip: "77406",
    price: 5000,
    priceType: "lease",
    beds: 5,
    baths: 5,
    sqft: 3840,
    lotSize: "0.25 acres",
    yearBuilt: 2019,
    propertyType: "Single Family Home",
    status: "For Lease",
    featured: true,
    description: "Welcome to this magnificent 5-bedroom, 5-bathroom estate located in the prestigious Aliana community of Richmond, TX. This stunning property offers over 3,800 square feet of luxurious living space, featuring high ceilings, an open floor plan, and premium finishes throughout. The gourmet kitchen boasts granite countertops, stainless steel appliances, and a large island perfect for entertaining. The primary suite is a true retreat with a spa-like bathroom and spacious walk-in closet. With a 3-car garage, covered patio, and beautifully landscaped yard, this home is perfect for families seeking the ultimate in comfort and style.",
    features: [
      "Open Floor Plan",
      "High Ceilings",
      "Granite Countertops",
      "Stainless Steel Appliances",
      "Primary Suite Retreat",
      "Spa-Like Bathroom",
      "Walk-in Closet",
      "3-Car Garage",
      "Covered Patio",
      "Smart Home Features",
      "Energy Efficient",
      "Community Pool",
    ],
    images: [
      "https://dlajgvw9htjpb.cloudfront.net/cms/0546c848-65fb-4216-bc9b-625e1eafc6bf/86221175/-2798420792025013588.jpg",
      listing1,
      listing2,
      listing3,
    ],
    virtualTourUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    matterportUrl: "https://my.matterport.com/show/?m=SxQL3iGyvWk",
    hoaFee: 150,
    garage: 3,
    stories: 2,
    heating: "Central",
    cooling: "Central Air",
    flooring: ["Hardwood", "Tile", "Carpet"],
    appliances: ["Refrigerator", "Dishwasher", "Microwave", "Oven", "Garbage Disposal"],
    neighborhood: "Aliana",
    school_district: "Fort Bend ISD",
    latitude: 29.5530,
    longitude: -95.7530,
    mlsNumber: "MLS-2024-001",
    daysOnMarket: 14,
  },
  {
    id: "7735-coburn-drive",
    title: "Charming 3-Bedroom Home in Beaumont",
    address: "7735 Coburn Drive",
    city: "Beaumont",
    state: "TX",
    zip: "77707",
    price: 175000,
    priceType: "sale",
    beds: 3,
    baths: 2,
    sqft: 2436,
    lotSize: "0.18 acres",
    yearBuilt: 1985,
    propertyType: "Single Family Home",
    status: "For Sale",
    featured: true,
    description: "This well-maintained 3-bedroom home offers exceptional value in a quiet Beaumont neighborhood. With over 2,400 square feet of living space, this property features a spacious living room, updated kitchen, and large bedrooms. The mature trees and landscaped yard provide privacy and curb appeal. Perfect for first-time buyers or investors looking for a solid property with great potential.",
    features: [
      "Updated Kitchen",
      "Large Bedrooms",
      "Mature Trees",
      "Landscaped Yard",
      "2-Car Garage",
      "Storage Space",
      "New HVAC",
      "Fresh Paint",
    ],
    images: [
      "https://dlajgvw9htjpb.cloudfront.net/cms/0546c848-65fb-4216-bc9b-625e1eafc6bf/6820929/-7189515740131590123.jpg",
      listing2,
      listing3,
      listing1,
    ],
    garage: 2,
    stories: 1,
    heating: "Central",
    cooling: "Central Air",
    flooring: ["Carpet", "Tile"],
    appliances: ["Refrigerator", "Dishwasher", "Range"],
    school_district: "Beaumont ISD",
    latitude: 30.0802,
    longitude: -94.1266,
    mlsNumber: "MLS-2024-002",
    daysOnMarket: 21,
  },
  {
    id: "8114-bassett-street",
    title: "Prime Land Opportunity in Houston",
    address: "8114 Bassett Street",
    city: "Houston",
    state: "TX",
    zip: "77061",
    price: 75000,
    priceType: "sale",
    beds: 0,
    baths: 0,
    sqft: 3001,
    lotSize: "3,001 sqft",
    propertyType: "Land",
    status: "For Sale",
    featured: true,
    description: "Exceptional opportunity to own a prime piece of land in Houston. This 3,001 square foot lot is perfect for building your dream home or investment property. Located in a growing area with easy access to major highways and amenities. Utilities available at the street. Don't miss this chance to invest in Houston's future!",
    features: [
      "Utilities Available",
      "Level Lot",
      "Easy Highway Access",
      "Growing Area",
      "Build Your Dream Home",
      "Investment Opportunity",
    ],
    images: [
      "https://dlajgvw9htjpb.cloudfront.net/cms/0546c848-65fb-4216-bc9b-625e1eafc6bf/40519433/7120993268281597033.jpg",
      listing3,
      listing1,
    ],
    latitude: 29.6750,
    longitude: -95.2990,
    mlsNumber: "MLS-2024-003",
    daysOnMarket: 45,
  },
  // MORE PROPERTIES FROM PORTFOLIO
  {
    id: "6802-mirabeau-lane",
    title: "Elegant 5-Bedroom in Katy",
    address: "6802 Mirabeau Lane",
    city: "Katy",
    state: "TX",
    zip: "77493",
    price: 5000,
    priceType: "lease",
    beds: 5,
    baths: 5,
    sqft: 4263,
    lotSize: "0.30 acres",
    yearBuilt: 2020,
    propertyType: "Single Family Home",
    status: "For Lease",
    featured: true,
    description: "Exquisite 5-bedroom estate in the heart of Katy. This stunning property features over 4,200 square feet of refined living space with soaring ceilings, designer finishes, and an open floor plan perfect for entertaining. The gourmet kitchen features premium appliances, quartz countertops, and a massive island. The primary suite offers a spa-like retreat with dual vanities and a walk-in closet. Enjoy resort-style living with a covered patio overlooking the manicured backyard.",
    features: [
      "Soaring Ceilings",
      "Designer Finishes",
      "Gourmet Kitchen",
      "Quartz Countertops",
      "Primary Suite Retreat",
      "Dual Vanities",
      "Walk-in Closet",
      "Covered Patio",
      "3-Car Garage",
      "Smart Home Ready",
    ],
    images: [
      "https://dlajgvw9htjpb.cloudfront.net/cms/0546c848-65fb-4216-bc9b-625e1eafc6bf/73444642/-7106235475037492513.jpg",
      listing1,
      listing2,
      listing3,
    ],
    hoaFee: 200,
    garage: 3,
    stories: 2,
    heating: "Central, Zoned",
    cooling: "Central Air, Zoned",
    flooring: ["Hardwood", "Tile", "Carpet"],
    appliances: ["Built-in Refrigerator", "Double Oven", "Gas Cooktop", "Dishwasher"],
    neighborhood: "Katy",
    school_district: "Katy ISD",
    latitude: 29.7853,
    longitude: -95.8177,
    mlsNumber: "MLS-2024-004",
    daysOnMarket: 7,
  },
  {
    id: "18419-windy-knoll-way",
    title: "Modern 4-Bedroom in Houston",
    address: "18419 Windy Knoll Way",
    city: "Houston",
    state: "TX",
    zip: "77084",
    price: 449990,
    priceType: "sale",
    beds: 4,
    baths: 3,
    sqft: 2799,
    lotSize: "0.20 acres",
    yearBuilt: 2021,
    propertyType: "Single Family Home",
    status: "For Sale",
    featured: true,
    description: "Welcome to this beautiful modern 4-bedroom home in a sought-after Houston neighborhood. This stunning property boasts nearly 2,800 square feet of contemporary living space with an open floor plan, high ceilings, and abundant natural light. The chef's kitchen features granite countertops, stainless steel appliances, and a breakfast bar. The spacious primary suite includes a luxurious bathroom with dual vanities and a walk-in closet. Enjoy outdoor living on the covered patio with a beautifully landscaped backyard.",
    features: [
      "Open Floor Plan",
      "High Ceilings",
      "Granite Countertops",
      "Stainless Steel Appliances",
      "Breakfast Bar",
      "Primary Suite",
      "Dual Vanities",
      "Walk-in Closet",
      "Covered Patio",
      "Landscaped Backyard",
    ],
    images: [
      "https://dlajgvw9htjpb.cloudfront.net/cms/0546c848-65fb-4216-bc9b-625e1eafc6bf/74000085/-3252337621568236283.jpg",
      listing2,
      listing1,
      listing3,
    ],
    hoaFee: 150,
    garage: 2,
    stories: 2,
    heating: "Central",
    cooling: "Central Air",
    flooring: ["Engineered Hardwood", "Tile", "Carpet"],
    appliances: ["Refrigerator", "Dishwasher", "Range", "Microwave"],
    neighborhood: "Cypress Creek Lakes",
    school_district: "Cypress-Fairbanks ISD",
    latitude: 29.8991,
    longitude: -95.6970,
    mlsNumber: "MLS-2024-005",
    daysOnMarket: 18,
  },
  {
    id: "2614-kenwich-oaks-lane",
    title: "Contemporary 4-Bedroom in Katy",
    address: "2614 Kenwich Oaks Lane",
    city: "Katy",
    state: "TX",
    zip: "77449",
    price: 299990,
    priceType: "sale",
    beds: 4,
    baths: 3,
    sqft: 2160,
    lotSize: "0.18 acres",
    yearBuilt: 2019,
    propertyType: "Single Family Home",
    status: "For Sale",
    featured: false,
    description: "This contemporary 4-bedroom home in Katy offers the perfect blend of style and functionality. With over 2,100 square feet, the open-concept living area flows seamlessly from the living room to the kitchen and dining area. The modern kitchen features quartz countertops, a large island, and updated appliances. Each bedroom is generously sized with ample closet space. Located in a family-friendly neighborhood with easy access to schools, shopping, and entertainment.",
    features: [
      "Open Concept",
      "Quartz Countertops",
      "Large Island",
      "Updated Appliances",
      "Generously Sized Bedrooms",
      "Ample Closet Space",
      "2-Car Garage",
      "Family-Friendly",
    ],
    images: [
      "https://dlajgvw9htjpb.cloudfront.net/cms/0546c848-65fb-4216-bc9b-625e1eafc6bf/79795045/327508728436734598.jpg",
      listing3,
      listing2,
      listing1,
    ],
    hoaFee: 125,
    garage: 2,
    stories: 2,
    heating: "Central",
    cooling: "Central Air",
    flooring: ["Luxury Vinyl Plank", "Tile", "Carpet"],
    appliances: ["Refrigerator", "Dishwasher", "Range"],
    neighborhood: "Katy",
    school_district: "Katy ISD",
    latitude: 29.7553,
    longitude: -95.7677,
    mlsNumber: "MLS-2024-006",
    daysOnMarket: 25,
  },
  {
    id: "14703-carolina-falls-lane",
    title: "Beautiful 4-Bedroom in Cypress",
    address: "14703 Carolina Falls Lane",
    city: "Cypress",
    state: "TX",
    zip: "77433",
    price: 290000,
    priceType: "sale",
    beds: 4,
    baths: 3,
    sqft: 2069,
    lotSize: "0.15 acres",
    yearBuilt: 2018,
    propertyType: "Single Family Home",
    status: "For Sale",
    featured: false,
    description: "Discover this beautiful 4-bedroom home in the scenic Cypress community. This well-maintained property features over 2,000 square feet of comfortable living space with an open floor plan, updated kitchen, and inviting living areas. The primary suite offers a private retreat with an ensuite bathroom and walk-in closet. Enjoy the covered patio and fenced backyard, perfect for outdoor entertaining or relaxing with family.",
    features: [
      "Open Floor Plan",
      "Updated Kitchen",
      "Primary Suite",
      "Ensuite Bathroom",
      "Walk-in Closet",
      "Covered Patio",
      "Fenced Backyard",
      "2-Car Garage",
    ],
    images: [
      "https://dlajgvw9htjpb.cloudfront.net/cms/0546c848-65fb-4216-bc9b-625e1eafc6bf/76947773/-5243027874929875930.jpg",
      listing1,
      listing3,
      listing2,
    ],
    hoaFee: 100,
    garage: 2,
    stories: 2,
    heating: "Central",
    cooling: "Central Air",
    flooring: ["Laminate", "Tile", "Carpet"],
    appliances: ["Refrigerator", "Dishwasher", "Range", "Microwave"],
    neighborhood: "Cypress Creek Lakes",
    school_district: "Cypress-Fairbanks ISD",
    latitude: 29.9291,
    longitude: -95.7070,
    mlsNumber: "MLS-2024-007",
    daysOnMarket: 32,
  },
  {
    id: "7218-rocky-ridge-lane",
    title: "Spacious 5-Bedroom in Richmond",
    address: "7218 Rocky Ridge Lane",
    city: "Richmond",
    state: "TX",
    zip: "77407",
    price: 434990,
    priceType: "sale",
    beds: 5,
    baths: 4,
    sqft: 3395,
    lotSize: "0.22 acres",
    yearBuilt: 2020,
    propertyType: "Single Family Home",
    status: "For Sale",
    featured: true,
    description: "Impressive 5-bedroom home in Richmond's desirable neighborhood. This spacious property offers nearly 3,400 square feet of elegant living space with high ceilings, crown molding, and premium finishes throughout. The chef's kitchen features granite countertops, custom cabinetry, and a large island with seating. The primary suite is a true sanctuary with a sitting area, spa bathroom, and custom closet. Multiple living areas and a game room provide ample space for family and entertaining.",
    features: [
      "High Ceilings",
      "Crown Molding",
      "Premium Finishes",
      "Granite Countertops",
      "Custom Cabinetry",
      "Large Island",
      "Sitting Area",
      "Spa Bathroom",
      "Custom Closet",
      "Game Room",
    ],
    images: [
      "https://dlajgvw9htjpb.cloudfront.net/cms/0546c848-65fb-4216-bc9b-625e1eafc6bf/87826221/8564039198595028051.jpg",
      listing2,
      listing1,
      listing3,
    ],
    hoaFee: 175,
    garage: 2,
    stories: 2,
    heating: "Central, Zoned",
    cooling: "Central Air, Zoned",
    flooring: ["Hardwood", "Tile", "Carpet"],
    appliances: ["Refrigerator", "Double Oven", "Gas Cooktop", "Dishwasher", "Wine Cooler"],
    neighborhood: "Greatwood",
    school_district: "Fort Bend ISD",
    latitude: 29.5730,
    longitude: -95.7330,
    mlsNumber: "MLS-2024-008",
    daysOnMarket: 12,
  },
  {
    id: "13600-breton-ridge-street",
    title: "Stylish 3-Bedroom Condo in Houston",
    address: "13600 Breton Ridge Street #36E",
    city: "Houston",
    state: "TX",
    zip: "77070",
    price: 227000,
    priceType: "sale",
    beds: 3,
    baths: 2,
    sqft: 1632,
    yearBuilt: 2015,
    propertyType: "Condo",
    status: "For Sale",
    featured: false,
    description: "Stylish 3-bedroom condo in the sought-after Breton Ridge community. This well-appointed unit features over 1,600 square feet of modern living space with an open floor plan, updated kitchen, and private balcony. The primary bedroom offers an ensuite bathroom and walk-in closet. Enjoy community amenities including a pool, fitness center, and clubhouse. Convenient location near shopping, dining, and major highways.",
    features: [
      "Open Floor Plan",
      "Updated Kitchen",
      "Private Balcony",
      "Ensuite Bathroom",
      "Walk-in Closet",
      "Community Pool",
      "Fitness Center",
      "Clubhouse",
    ],
    images: [
      "https://dlajgvw9htjpb.cloudfront.net/cms/0546c848-65fb-4216-bc9b-625e1eafc6bf/24280518/-1281652502502408257.jpg",
      listing3,
      listing2,
      listing1,
    ],
    hoaFee: 350,
    stories: 1,
    heating: "Central",
    cooling: "Central Air",
    flooring: ["Laminate", "Tile"],
    appliances: ["Refrigerator", "Dishwasher", "Range", "Microwave"],
    neighborhood: "Breton Ridge",
    school_district: "Spring Branch ISD",
    latitude: 29.8702,
    longitude: -95.5566,
    mlsNumber: "MLS-2024-009",
    daysOnMarket: 40,
  },
  {
    id: "14435-andrea-way-lane",
    title: "Executive 5-Bedroom in Cypress",
    address: "14435 Andrea Way Lane",
    city: "Cypress",
    state: "TX",
    zip: "77429",
    price: 369990,
    priceType: "sale",
    beds: 5,
    baths: 3,
    sqft: 3038,
    lotSize: "0.20 acres",
    yearBuilt: 2019,
    propertyType: "Single Family Home",
    status: "For Sale",
    featured: false,
    description: "Executive 5-bedroom home in Cypress offering over 3,000 square feet of sophisticated living space. This stunning property features an open floor plan with soaring ceilings, gourmet kitchen, and elegant finishes throughout. The primary suite is a private retreat with a luxurious bathroom featuring dual vanities, garden tub, and separate shower. Additional bedrooms are generously sized with ample closet space. Enjoy outdoor living on the covered patio with a beautifully landscaped yard.",
    features: [
      "Soaring Ceilings",
      "Gourmet Kitchen",
      "Elegant Finishes",
      "Primary Suite",
      "Dual Vanities",
      "Garden Tub",
      "Separate Shower",
      "Covered Patio",
      "Landscaped Yard",
      "3-Car Garage",
    ],
    images: [
      "https://dlajgvw9htjpb.cloudfront.net/cms/0546c848-65fb-4216-bc9b-625e1eafc6bf/33975930/6008241602089556706.jpg",
      listing1,
      listing2,
      listing3,
    ],
    hoaFee: 150,
    garage: 3,
    stories: 2,
    heating: "Central",
    cooling: "Central Air",
    flooring: ["Hardwood", "Tile", "Carpet"],
    appliances: ["Refrigerator", "Double Oven", "Gas Cooktop", "Dishwasher"],
    neighborhood: "Bridgeland",
    school_district: "Cypress-Fairbanks ISD",
    latitude: 29.9591,
    longitude: -95.6770,
    mlsNumber: "MLS-2024-010",
    daysOnMarket: 22,
  },
  {
    id: "327-cavalry-trail-drive",
    title: "Premium Land in Rosharon",
    address: "327 Cavalry Trail Drive",
    city: "Rosharon",
    state: "TX",
    zip: "77583",
    price: 99990,
    priceType: "sale",
    beds: 0,
    baths: 0,
    sqft: 43560,
    lotSize: "1 acre",
    propertyType: "Land",
    status: "For Sale",
    featured: false,
    description: "Premium 1-acre lot in Rosharon, perfect for building your dream home. This exceptional property offers privacy and space with easy access to highways and amenities. Utilities are available at the street, and the lot is ready for construction. Located in a growing community with new developments nearby. Don't miss this opportunity to own a piece of Texas!",
    features: [
      "1 Acre Lot",
      "Privacy",
      "Utilities Available",
      "Ready for Construction",
      "Easy Highway Access",
      "Growing Community",
    ],
    images: [
      "https://dlajgvw9htjpb.cloudfront.net/cms/0546c848-65fb-4216-bc9b-625e1eafc6bf/30553656/-3680443779631392670.jpg",
      listing2,
      listing3,
    ],
    latitude: 29.3550,
    longitude: -95.4530,
    mlsNumber: "MLS-2024-011",
    daysOnMarket: 60,
  },
  // Additional premium listings for immersive experience
  {
    id: "sugar-land-luxury-estate",
    title: "Luxury Estate in Sugar Land",
    address: "4521 Sweetwater Blvd",
    city: "Sugar Land",
    state: "TX",
    zip: "77479",
    price: 1250000,
    priceType: "sale",
    beds: 5,
    baths: 5,
    sqft: 4800,
    lotSize: "0.35 acres",
    yearBuilt: 2021,
    propertyType: "Single Family Home",
    status: "For Sale",
    featured: true,
    description: "Experience unparalleled luxury in this stunning Sugar Land estate. This architectural masterpiece features 5 bedrooms, 5 bathrooms, and nearly 5,000 square feet of impeccable design. The grand foyer leads to soaring ceilings and walls of windows that flood the home with natural light. The chef's kitchen features top-of-the-line appliances, custom cabinetry, and a massive island. The primary suite is a private sanctuary with a sitting area, spa bathroom, and custom closet. The outdoor living space includes a covered patio, summer kitchen, and resort-style pool.",
    features: [
      "Resort-Style Pool",
      "Summer Kitchen",
      "Smart Home Technology",
      "Wine Cellar",
      "Home Theater",
      "Custom Closets",
      "3-Car Garage",
      "Gated Community",
      "Top-Rated Schools",
      "Energy Star Certified",
    ],
    images: [
      listing1,
      listing2,
      listing3,
    ],
    virtualTourUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    matterportUrl: "https://my.matterport.com/show/?m=SxQL3iGyvWk",
    hoaFee: 350,
    garage: 3,
    stories: 2,
    heating: "Central, Zoned",
    cooling: "Central Air, Zoned",
    flooring: ["Hardwood", "Marble", "Carpet"],
    appliances: ["Built-in Refrigerator", "Double Oven", "Gas Cooktop", "Wine Cooler", "Dishwasher"],
    neighborhood: "Sweetwater",
    school_district: "Fort Bend ISD",
    latitude: 29.5827,
    longitude: -95.6345,
    mlsNumber: "MLS-2024-012",
    daysOnMarket: 7,
  },
  {
    id: "missouri-city-modern",
    title: "Modern Masterpiece in Missouri City",
    address: "8742 Sienna Springs Blvd",
    city: "Missouri City",
    state: "TX",
    zip: "77459",
    price: 575000,
    priceType: "sale",
    beds: 4,
    baths: 4,
    sqft: 3200,
    lotSize: "0.25 acres",
    yearBuilt: 2022,
    propertyType: "Single Family Home",
    status: "For Sale",
    featured: true,
    description: "Modern living at its finest in Missouri City's premier Sienna Springs community. This stunning 4-bedroom home features contemporary architecture, an open floor plan, and high-end finishes throughout. The gourmet kitchen is a chef's dream with quartz countertops, premium appliances, and a large island. The primary suite offers a spa-like bathroom with freestanding tub and walk-in shower. Enjoy seamless indoor-outdoor living with a covered patio and beautifully landscaped backyard.",
    features: [
      "Contemporary Architecture",
      "Open Floor Plan",
      "Quartz Countertops",
      "Premium Appliances",
      "Spa-Like Bathroom",
      "Freestanding Tub",
      "Walk-in Shower",
      "Covered Patio",
      "Smart Home Features",
      "Energy Efficient",
    ],
    images: [
      listing2,
      listing1,
      listing3,
    ],
    hoaFee: 200,
    garage: 2,
    stories: 2,
    heating: "Central",
    cooling: "Central Air",
    flooring: ["Engineered Hardwood", "Tile", "Carpet"],
    appliances: ["Refrigerator", "Double Oven", "Gas Cooktop", "Dishwasher"],
    neighborhood: "Sienna Springs",
    school_district: "Fort Bend ISD",
    latitude: 29.5327,
    longitude: -95.5845,
    mlsNumber: "MLS-2024-013",
    daysOnMarket: 15,
  },
  {
    id: "pearland-family-home",
    title: "Spacious Family Home in Pearland",
    address: "3218 Shadow Creek Pkwy",
    city: "Pearland",
    state: "TX",
    zip: "77584",
    price: 425000,
    priceType: "sale",
    beds: 4,
    baths: 3,
    sqft: 2850,
    lotSize: "0.20 acres",
    yearBuilt: 2020,
    propertyType: "Single Family Home",
    status: "For Sale",
    featured: false,
    description: "Welcome to this spacious family home in Pearland's desirable Shadow Creek community. This 4-bedroom property offers nearly 2,900 square feet of comfortable living with an open floor plan, updated kitchen, and multiple living areas. The primary suite features a luxurious bathroom and walk-in closet. Enjoy outdoor living on the covered patio with a fenced backyard perfect for kids and pets. Located near top-rated schools, shopping, and dining.",
    features: [
      "Open Floor Plan",
      "Updated Kitchen",
      "Multiple Living Areas",
      "Luxurious Bathroom",
      "Walk-in Closet",
      "Covered Patio",
      "Fenced Backyard",
      "Top-Rated Schools",
    ],
    images: [
      listing3,
      listing2,
      listing1,
    ],
    hoaFee: 175,
    garage: 2,
    stories: 2,
    heating: "Central",
    cooling: "Central Air",
    flooring: ["Hardwood", "Tile", "Carpet"],
    appliances: ["Refrigerator", "Dishwasher", "Range", "Microwave"],
    neighborhood: "Shadow Creek",
    school_district: "Pearland ISD",
    latitude: 29.5227,
    longitude: -95.2945,
    mlsNumber: "MLS-2024-014",
    daysOnMarket: 28,
  },
  {
    id: "rosenberg-new-construction",
    title: "New Construction in Rosenberg",
    address: "5612 Grand River Blvd",
    city: "Rosenberg",
    state: "TX",
    zip: "77471",
    price: 385000,
    priceType: "sale",
    beds: 4,
    baths: 3,
    sqft: 2650,
    lotSize: "0.18 acres",
    yearBuilt: 2024,
    propertyType: "Single Family Home",
    status: "For Sale",
    featured: false,
    description: "Brand new construction in Rosenberg's growing Grand River community. This stunning 4-bedroom home features modern design, premium finishes, and energy-efficient construction. The open floor plan includes a gourmet kitchen with granite countertops, stainless steel appliances, and a large island. The primary suite offers a spa-like bathroom and custom closet. Builder warranties included. Move-in ready!",
    features: [
      "New Construction",
      "Modern Design",
      "Premium Finishes",
      "Energy Efficient",
      "Granite Countertops",
      "Stainless Steel Appliances",
      "Spa-Like Bathroom",
      "Custom Closet",
      "Builder Warranties",
      "Move-in Ready",
    ],
    images: [
      listing1,
      listing3,
      listing2,
    ],
    hoaFee: 125,
    garage: 2,
    stories: 2,
    heating: "Central",
    cooling: "Central Air",
    flooring: ["Luxury Vinyl Plank", "Tile", "Carpet"],
    appliances: ["Refrigerator", "Dishwasher", "Range", "Microwave"],
    neighborhood: "Grand River",
    school_district: "Lamar CISD",
    latitude: 29.5527,
    longitude: -95.8045,
    mlsNumber: "MLS-2024-015",
    daysOnMarket: 5,
  },
];

export function getListingById(id: string): PropertyListing | undefined {
  return allListings.find((listing) => listing.id === id);
}

export function formatPrice(price: number, priceType: "sale" | "lease" = "sale"): string {
  const formatted = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
  }).format(price);
  return priceType === "lease" ? `${formatted}/mo` : formatted;
}

export function getFeaturedListings(): PropertyListing[] {
  return allListings.filter((listing) => listing.featured);
}

export function getListingsByCriteria(criteria: {
  city?: string;
  propertyType?: string;
  minPrice?: number;
  maxPrice?: number;
  minBeds?: number;
  minBaths?: number;
  status?: string;
}): PropertyListing[] {
  return allListings.filter((listing) => {
    if (criteria.city && listing.city !== criteria.city) return false;
    if (criteria.propertyType && listing.propertyType !== criteria.propertyType) return false;
    if (criteria.minPrice && listing.price < criteria.minPrice) return false;
    if (criteria.maxPrice && listing.price > criteria.maxPrice) return false;
    if (criteria.minBeds && listing.beds < criteria.minBeds) return false;
    if (criteria.minBaths && listing.baths < criteria.minBaths) return false;
    if (criteria.status && listing.status !== criteria.status) return false;
    return true;
  });
}

export const propertyTypes = [
  "Single Family Home",
  "Townhouse", 
  "Condo",
  "Land",
  "Multi-Family",
] as const;

export const cities = [
  "Houston",
  "Sugar Land",
  "Katy",
  "Cypress",
  "Richmond",
  "Missouri City",
  "Pearland",
  "Rosenberg",
  "Rosharon",
  "Beaumont",
] as const;

export const priceRanges = [
  { label: "Any Price", min: 0, max: Infinity },
  { label: "Under $200K", min: 0, max: 200000 },
  { label: "$200K - $300K", min: 200000, max: 300000 },
  { label: "$300K - $400K", min: 300000, max: 400000 },
  { label: "$400K - $500K", min: 400000, max: 500000 },
  { label: "$500K - $750K", min: 500000, max: 750000 },
  { label: "$750K - $1M", min: 750000, max: 1000000 },
  { label: "$1M+", min: 1000000, max: Infinity },
];

export const bedOptions = [
  { label: "Any", value: 0 },
  { label: "1+", value: 1 },
  { label: "2+", value: 2 },
  { label: "3+", value: 3 },
  { label: "4+", value: 4 },
  { label: "5+", value: 5 },
];

export const bathOptions = [
  { label: "Any", value: 0 },
  { label: "1+", value: 1 },
  { label: "2+", value: 2 },
  { label: "3+", value: 3 },
  { label: "4+", value: 4 },
];
